config/routes.rb
Rails.application.routes.draw do
  resources :workouts do
      resources :exercises
  end
  root "workouts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  belongs_to :workout
end

app/models/workout.rb
class Workout < ApplicationRecord
  has_many :exercises, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController

  def create
    @workout = Workout.find(params[:workout_id])
    @exercise = @workout.exercises.create(params[:exercise].permit(:name, :sets, :reps))
    redirect_to workout_path(@workout)
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :find_workout, only: [:show, :edit, :update, :destroy]
  def index
    @workouts = Workout.all.order("created_at DESC")
  end

  def show

  end

  def new
    @workout = Workout.new
  end

  def create
    @workout = Workout.new(workout_params)

    if @workout.save
      redirect_to @workout
    else
      render :new
    end
  end


  def edit

  end

  def update
    if @workout.update(workout_params)
      redirect_to @workout
    else
      render :edit
    end
  end

  def destroy
    @workout.destroy
      redirect_to root_path
  end


  private

  def workout_params
    params.require(:workout).permit(:date, :workout, :mood, :length)
  end

  def find_workout
    @workout = Workout.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/exercises/_exercise.html.erb
<p><%= exercise.name %></p>
<p><%= exercise.sets %></p>
<p><%= exercise.reps %></p>

app/views/exercises/_form.html.erb
<%= simple_form_for([@workout, @workout.exercises.build]) do |f| %>
  <%= f.input :name, input_html: {class: "form-control"}%>
  <%= f.input :sets, input_html: {class: "form-control"}%>
  <%= f.input :reps, input_html: {class: "form-control"}%>
  <br>
  <%= f.button :submit %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WorkoutLog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <%= link_to "Workout Log", root_path, class: "navbar-brand" %>
        </div>
        <div class="nav navbar-nav navbar-right ">
          <%= link_to "New Workout", new_workout_path, class: "navbar-link" %>
        </div>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/workouts/_form.html.erb
<%= simple_form_for(@workout, html: {class: "form-horizontal"}) do |f| %>
  <%= f.input :date, label: "Date", input_html: {class: "from-control"}%>
  <%= f.input :workout, label: "What area did you workout?", input_html: {class: "from-control"}%>
  <%= f.input :mood, label: "How are you feeling?", input_html: {class: "from-control"}%>
  <%= f.input :length, label: "How long was the workout?", input_html: {class: "from-control"}%>
  <br>
  <%= f.button :submit %>
<% end %>

app/views/workouts/edit.html.erb
<h1>Edit Workout</h1>
<%= render "form"%>
<%= link_to "Cancel", root_path%>

app/views/workouts/index.html.erb
<div id="index-workouts">
  <% @workouts.each do |workout|%>
    <h2><%= link_to workout.date.strftime("%A %B %d"), workout_path(workout) %></h2>
    <h3> <span>Workout:</span> <%= workout.workout %></h3>
  <% end %>
</div>

app/views/workouts/new.html.erb
<h1>New Workout</h1>
<%= render "form"%>
<%= link_to "Cancel", root_path%>

app/views/workouts/show.html.erb
<div id="workout">
  <p><%= @workout.date %></p>
  <p><%= @workout.workout %></p>
  <p><%= @workout.mood %></p>
  <p><%= @workout.length %></p>
</div>

<div id="exercises">
  <h2>Exercises</h2>
  <%= render @workout.exercises %>
  <h3>Add an exercise</h3>
  <%= render "exercises/form"%>
</div>
<%= link_to "Back", root_path %> |
<%= link_to "Edit", edit_workout_path %> |
<%= link_to "Delete", workout_path(@workout), method: :delete, data: {confirm: "Are you sure?"}%>